---
title: "hw5_exercise"
output: html_document
date: "2023-02-21"
---

## Problem 1 
In lecture code, we compute the bootstrap confidence interval, but not the studendized version. In this homework exercise, we are going to perform this. 


```{r}
library("MASS")
original_data <- log(mammals)

bootLS <- function(x, y, student = "yes", conf = 0.95, B = 1000) {
  
  dat <- data.frame(x,y)
  n = nrow(dat) # sample size
  B = 1e3 # size of MC loop
  alpha = 1 - conf
  lower = (alpha/2)*B
  upper = (1-alpha/2)*B
  
  fit = lm(y ~ x, data = dat) # the original fit 
  inte <- fit$coefficients[1]
  slope <- fit$coefficients[2]
  
  intercept_boot <- numeric(B)
  slope_boot <- numeric(B)
  sigma_hat_boot <- numeric(B)
  c_int_boot <- numeric(B)
  c_slope_boot <- numeric(B)

  
  for (b in 1:B){
    
    dat_boot <- dat[sample(n, n, TRUE), ] # bootstrap sample
    fit_boot <- lm(y ~ x, data = dat_boot)
    
    intercept_boot[b] <- coef(fit_boot)[1]
    slope_boot[b] <- coef(fit_boot)[2]
    
    resi <- residuals(fit_boot)
    rss <- sum(resi^2)
    sigma_hat_boot[b] <- rss / (n-2)
    
    c_boot <- solve(t(model.matrix(fit_boot)) %*% model.matrix(fit_boot))
    
    c_int_boot[b] <- c_boot[1,1]
    c_slope_boot[b] <- c_boot[2,2]
    
  }

  intercept_boot <- sort(intercept_boot)
  slope_boot <- sort(slope_boot)
  sigma_hat_boot <- sort(sigma_hat_boot)
  c_int_boot <- sort(c_int_boot)
  c_slope_boot <- sort(c_slope_boot)
  
  stu_ci_intercept <- c(  inte -  (intercept_boot[upper] - inte)/(sigma_hat_boot[upper] * sqrt(c_int_boot[upper]))  ,  
                      inte -  (intercept_boot[lower] - inte)/(sigma_hat_boot[lower] * sqrt(c_int_boot[lower])) )
  # Problematic: if you read the correct answer, you will see that you can use summary(fit)$coefficients[,2] to 
  # get the standard deviation, so that you don't actually have to compute 
  # (sigma_hat_boot[upper] * sqrt(c_int_boot[upper])). The issue you have here is that t.upper (follow the notation
  # in the solution) does not equal to (sigma_hat_boot[upper] * sqrt(c_int_boot[upper])), where upper is the same 
  # quantile level. 
  
  
  stu_ci_slope <- c(  slope -  (slope_boot[upper] - slope)/(sigma_hat_boot[upper] * sqrt(c_slope_boot[upper]))  ,  
                      slope -  (slope_boot[lower] - slope)/(sigma_hat_boot[lower] * sqrt(c_slope_boot[lower])) )
  
  ci_intercept <- c( 2 * inte - intercept_boot[upper]  , 2 * inte - intercept_boot[lower] )
  ci_slope <- c( 2 * slope - slope_boot[upper]  , 2 * slope - slope_boot[lower]  )
  
  if (student == "yes") {
    return(list(stu_ci_intercept, stu_ci_slope))
  } else {
    return(list(ci_intercept, ci_slope))
  }
}


fit = lm(brain ~ body, data = original_data)

# regular CI
confint(fit, level = 0.95)

# bootstrap CI. My result aligns with the lecture results 
ci_boot <- bootLS(original_data$body, original_data$brain, student = "no", conf = 0.95, B = 1000)


# studentized bootstrap CI. something is off.. this suppose to be more accurate than tne bootstrap CI. 
studentized_ci_boot <- bootLS(original_data$body, original_data$brain, student = "yes", conf = 0.95, B = 1000)

```


## Problem 2 

```{r}

analyze <- function(n, dist = "normal" ) {
  n = 20
  x <- runif(n, 0, 1)
  if (dist == "normal") {
    y <- 3 + 2*x + rnorm(n, 0, 1)
  } else {
    y <- 3 + 2*x + rexp(n, 1) # to do: centered so that mean of the error is 0 
  }
  
  ci_boot <- bootLS(x, y, student = "no", conf = 0.95, B = 1000)
  pivot_ci_boot <- bootLS(x, y, student = "yes", conf = 0.95, B = 1000)

  ci_boot_int_length <- ci_boot[[1]][2] - ci_boot[[1]][1]
  ci_boot_slope_length <- ci_boot[[2]][2] - ci_boot[[2]][1]

  pivot_ci_boot_int_length <- pivot_ci_boot[[1]][2] - pivot_ci_boot[[1]][1]
  pivot_ci_boot_slope_length <- pivot_ci_boot[[2]][2] - pivot_ci_boot[[2]][1]
  
  return(list(ci_boot_int_length, ci_boot_slope_length, pivot_ci_boot_int_length, pivot_ci_boot_slope_length))
}


 test_20 <- unlist(analyze(20, dist = "normal"))
 test_50 <- unlist(analyze(50, dist = "normal"))
 test_100 <- unlist(analyze(100, dist = "normal"))
 test_150 <- unlist(analyze(150, dist = "normal"))
 test_200 <- unlist(analyze(200, dist = "normal"))
 test_250 <- unlist(analyze(250, dist = "normal"))
 test_300 <- unlist(analyze(300, dist = "normal"))

 compare <- rbind(test_20, test_50, test_100, test_150, test_200, test_250, test_300)
# hmmm did not see a clear pattern. I was looking for the pattern that as n increase, the length of the interval decreases. 


```









